### ISSUE TITLE
Event map assignment - PanDDA export

### ISSUE THREAD

**Issue by reskyner** [xchem/XChemExplorer#12]
During export of pandda results, the event maps are not assigned to the respective events in the panddaTable; one needs to run 'update database from file system' for this to happen.

* But the 'update database from filesystem' seems to overwrite RefinementOutcome status; or more precisely, it sets datasets that are already compchen-ready back to in refinement

**Comment by nelse003** [comment]
Everybody thinks Tobias fixed it, Romain hasn't seen for a long time.
