### ISSUE TITLE
Twinned data with dimple - custom dimple install request

### ISSUE THREAD

**Issue by reskyner** [xchem/XChemExplorer#126]
Hi Rachael,
 
How straightforward is it to have a tweaked version of dimple which allows for refining with twinned data? See marcin’s last email below.
 
Jose’
 
From: Brandao-Neto, Jose (DLSLtd,RAL,LSCI) 
Sent: 12 January 2018 09:34
To: 'Marcin Wojdyr'; Talapatra, Sandeep
Subject: RE: dimple on twinned data
 
Hi marcin and sandeep, that's real great! I'm tied up all day today, tho.
 
The dimple installation at diamond is also something that is controlled centrally.
 
I can iterate a bit. I see the command line tells me this:
[jrb34@ws072 Desktop]$ which dimple
/dls_sw/apps/ccp4/64/7.0/update48/ccp4-7.0/bin/dimple
 
Jose’
 
-----Original Message-----
From: Marcin Wojdyr [mailto:wojdyr@gmail.com] 
Sent: 11 January 2018 18:52
To: Talapatra, Sandeep
Cc: Brandao-Neto, Jose (DLSLtd,RAL,LSCI)
Subject: Re: dimple on twinned data
 
OK, I added an option --refmac-key to Dimple.
You'd need to find a file dimple/main.py and replace it with:
https://raw.githubusercontent.com/ccp4/dimple/master/main.py
 
Then you'd run:
dimple --refmac-key 'refi tlsc' ...
but instead of "refi tlsc" put keywords that you need.
 
Hope this helps,
Marcin
 
On 11 January 2018 at 17:53, Talapatra, Sandeep <s.talapatra@ucl.ac.uk> wrote:
> I can try it with our datasets if you want me to. That would be a
> great and easier thing to do for us than usual MR and then refmac
> 
> 
> 
> Sent from my Samsung Galaxy smartphone.
> 
> 
> -------- Original message --------
> From: Marcin Wojdyr <wojdyr@gmail.com>
> Date: 11/01/2018 5:38 pm (GMT+00:00)
> To: "Talapatra, Sandeep" <s.talapatra@ucl.ac.uk>
> Cc: "jose.brandao-neto" <jose.brandao-neto@diamond.ac.uk>
> Subject: Re: dimple on twinned data
> 
> Just to clarify: I meant that such feature could be added quickly, but
> it doesn't exist currently.
> If Tobias or whoever manages XCE would pick up on this, we could get
> it done.
> It'd require some testing from the interested parties before the
> change is propagated to the CCP4 updates.
> Cheers,
> Marcin
> 
> On 11 January 2018 at 17:30, Talapatra, Sandeep
> <s.talapatra@ucl.ac.uk>
> wrote:
>> 
>> Right, ok then I will have to wait for the XCE to get updated with
>> the new feature later sometime then.
>> 
>> 
>> Thanks anyways
>> 
>> ________________________________
>> From: Marcin Wojdyr <wojdyr@gmail.com>
>> Sent: 11 January 2018 17:28:21
>> 
>> To: Talapatra, Sandeep
>> Cc: jose.brandao-neto
>> Subject: Re: dimple on twinned data
>> 
>> Well, it may not be possible.
>> Currently deployed version of Dimple doesn't have an option to add
>> custom Refmac keywords.
>> So to add some keywords you would need to use a separate Dimple
>> installation that you could modify. I don't know if it can be organized.
>> Marcin
>> 
>> On 11 January 2018 at 17:21, Talapatra, Sandeep
>> <s.talapatra@ucl.ac.uk>
>> wrote:
>> 
>> Hi Marcin,
>> 
>> 
>> Sorry if I am quite naive about this.
>> 
>> 
>> But maybe this link might help for the keywords in Refmac.
>> 
>> 
>> http://www.ccp4.ac.uk/html/refmac5/keywords/keywords_5_5.html
>> 
>> refmac keywords - CCP4
>> www.ccp4.ac.uk
>> refmac keywords (version 5.5.0026 and later) Please note that most of
>> these keywords were in the previous versions also. Some of the
>> keywords were implemented as user ...
>> 
>> 
>> 
>> Also, I am working at Diamond cluster, I do not know if I understand
>> correctly but you want me to modify something in the local Dimple
>> that I use?
>> 
>> 
>> Thanks
>> 
>> Sandeep
>> 
>> ________________________________
>> From: Marcin Wojdyr <wojdyr@gmail.com>
>> Sent: 11 January 2018 17:14:50
>> To: Talapatra, Sandeep
>> Cc: jose.brandao-neto
>> 
>> Subject: Re: dimple on twinned data
>> 
>> Hi Sandeep,
>> 
>> if you could determine how this GUI option is translated to Refmac
>> keywords, and if you can modify your local Dimple (CCP4?)
>> installation, we could probably make it work.
>> I'd send you one or two modified dimple files that you'd need to copy
>> over.
>> 
>> Cheers,
>> Marcin
>> 
>> On 11 January 2018 at 16:55, Talapatra, Sandeep
>> <s.talapatra@ucl.ac.uk>
>> wrote:
>> > Dear Marcin,
>> >
>> >
>> > I am not sure if this will help. But I have attached the screenshot
>> > of the gui based refmac where we do the twin refinement (marked in
>> > red).
>> >
>> >
>> > Thanks
>> >
>> > Sandeep
>> >
>> > ________________________________
>> > From: Marcin Wojdyr <wojdyr@gmail.com>
>> > Sent: 11 January 2018 16:49:48
>> > To: jose.brandao-neto
>> > Cc: Talapatra, Sandeep
>> > Subject: Re: dimple on twinned data
>> >
>> > Hi Jose,
>> >
>> > all is well here, I hope everything is going well in Diamond as well.
>> >
>> > There is for sure no such flag in Dimple now.
>> > If you know how to tell refmac to do the thing that you need, I can
>> > look into it.
>> >
>> > Marcin
>> >
>> > On 11 January 2018 at 16:44,  <jose.brandao-neto@diamond.ac.uk> wrote:
>> >> Hi Marcin,
>> >>
>> >>
>> >>
>> >> Long time no hear, I hope all is going well.
>> >>
>> >>
>> >>
>> >> I got a user (Sandeep, copied) running dimple on many tens of
>> >> datasets and would like to have dimple tell refmac to do twinning
>> >> refinement using amplitudes (and intensities independently). Is
>> >> there a flag for that?
>> >>
>> >>
>> >>
>> >> Cheers,
>> >>
>> >> Jose’
>> >>
>> >>
>> >>
>> >> ====================================
>> >> Jose Ribeiro Brandao-Neto MPhil CPhys Senior Beamline Scientist -
>> >> I04-1
>> >>
>> >> XChem Scientist
>> >> Macromolecular Crystallography Group
>> >>
>> >> Diamond Light Source Ltd
>> >> Diamond House DR1.78
>> >> Harwell Science and Innovation Campus RAL, Chilton, Didcot
>> >> Oxfordshire
>> >> OX11 0DE
>> >> United Kingdom
>> >>
>> >>
>> >>
>> >> tel: +44 (0)1235 778506
>> >>      +44 (0)1235 778000
>> >> fax: +44 (0)1235 778448
>> >>
>> >> jose.brandao-neto@diamond.ac.uk
>> >> http://www.diamond.ac.uk
>> >> ====================================
>> >>
>> >>
>> >>
>> >>
>> >>
>> >> --
>> >>
>> >> This e-mail and any attachments may contain confidential,
>> >> copyright and or privileged material, and are for the use of the
>> >> intended addressee only.
>> >> If
>> >> you are not the intended addressee or an authorised recipient of
>> >> the addressee please notify us of receipt by returning the e-mail
>> >> and do not use, copy, retain, distribute or disclose the
>> >> information in or attached to the e-mail.
>> >> Any opinions expressed within this e-mail are those of the
>> >> individual and not necessarily of Diamond Light Source Ltd.
>> >> Diamond Light Source Ltd. cannot guarantee that this e-mail or any
>> >> attachments are free from viruses and we cannot accept liability
>> >> for any damage which you may sustain as a result of software
>> >> viruses which may be transmitted in or with the message.
>> >> Diamond Light Source Limited (company no. 4375679). Registered in
>> >> England and Wales with its registered office at Diamond House,
>> >> Harwell Science and Innovation Campus, Didcot, Oxfordshire, OX11
>> >> 0DE, United Kingdom

**Comment by tkrojer** [comment]
implemented; see related issue
