### ISSUE TITLE
maps tab: xce doesn't respect a manual reference model selection

### ISSUE THREAD

**Issue by PatrickMCollins** [xchem/XChemExplorer#127]
Relates to the maps tab:

I have a few models in the reference directory.

If I select a particular model from the top right dropdown, and click Set New Reference, all datasets then have the selected model applied in the Reference File column (good). But then when I go to Run DIMPLE on selected MTZ files, I see that the input models used for dime go back to an auto selection of models based on the cell vol difference. And then the maps table also reverts back to the auto-selection.

For example:
for this dataset: OXA10-x0167 I have selected **OXA10-x0160** as the reference model, but when I look in the dimple log, I see that it has picked up and used OXA10-x0146_dimple.pdb as the reference instead. 

/dls/labxchem/data/2017/lb16949-4/processing/analysis/initial_model/OXA10-x0167/dimple/dimple_rerun_on_selected_file/dimple/dimple.log

grep "OXA10-x0146_dimple.pdb" dimple.log
 /dls/labxchem/data/2017/lb16949-4/processing/reference/OXA10-x0146_dimple.pdb
# 87c09519c4087b9bc3cf83eae400fcd9 /dls/labxchem/data/2017/lb16949-4/processing/reference/OXA10-x0146_dimple.pdb
pdb_files: ["/dls/labxchem/data/2017/lb16949-4/processing/reference/OXA10-x0146_dimple.pdb"]
# OXA10-x0146_dimple.pdb P 21 21 21   (48.27, 93.46, 125.18,  90, 90, 90)

Workaround is to remove the model from the reference directory.

This is important sine when people select a single reference to refine all their datasets to, in actual fact mixture of input models may be used unknowingly.

**Comment by tkrojer** [comment]
Also: select a certain reference model from the dropdown, then run 'set new reference if applicable'
