### ISSUE TITLE
Pandda table: doesn't always contain right info

### ISSUE THREAD

**Issue by reskyner** [xchem/XChemExplorer#147]
@tkrojer said the way the pandda table is populated needs a rethink. Specifically, linking ligands to events is a pain, as that information is not recorded anywhere. 

I said I had to do something similar for Anthony via Luigi, so I would have a look

The version implemented in Luigi/ the pipeline: https://github.com/xchem/pipeline/blob/master/luigi_classes/pandda_for_tindspect.py

**Comment by nelse003** [comment]
Been superceded by other stuff of Rachael (XCDB)
