### ISSUE TITLE
pandda event map scaling in xce-coot

### ISSUE THREAD

**Issue by PatrickMCollins** [xchem/XChemExplorer#169]
Hi All,
 
In pandda inspect, Nick has set the default event map scaling to 2 sigma. (Note: not the rmsd value reported by coot, as Nick explains in the helpful popup window, but the e/A^3 value divided by 1-BDC for the map).**
 
But in xce-coot, the maps are scaled by default to coot’s reported 2 rmsd value, and have a different contour level to that shown in pandda inspect.
 
I was wondering why I had the feeling that the event maps were looking worse in xce-coot than I had remembered when building in pandda inspect.
 
Not a big deal, flick the mouse wheel and chance the contour, but it would be good to a matching starting point.
 
Cheers,
Patrick
 
** If I understand correctly!!

**Comment by tkrojer** [comment]
Hi Patrick,

you raise a good point! I won’t be able to update this immediately, but will try doing it in May. In the meantime you will have to flick the mouse wheel.

Thanks,
Tobias




On 19 Apr 2018, at 10:08, PatrickMCollins <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi All,

In pandda inspect, Nick has set the default event map scaling to 2 sigma. (Note: not the rmsd value reported by coot, as Nick explains in the helpful popup window, but the e/A^3 value divided by 1-BDC for the map).**

But in xce-coot, the maps are scaled by default to coot’s reported 2 rmsd value, and have a different contour level to that shown in pandda inspect.

I was wondering why I had the feeling that the event maps were looking worse in xce-coot than I had remembered when building in pandda inspect.

Not a big deal, flick the mouse wheel and chance the contour, but it would be good to a matching starting point.

Cheers,
Patrick

** If I understand correctly!!

**Comment by tkrojer** [comment]
see #170
