### ISSUE TITLE
deposition of all apo structures as a single mmcif file

### ISSUE THREAD

**Issue by tkrojer** [xchem/XChemExplorer#215]

**Comment by tkrojer** [comment]
need to update data_ field in SF mmcif file:
data_rxxxxsf
data_rxxxxAsf
data_rxxxxBsf
etc.

**Comment by nelse003** [comment]
Please add a finished line to the apo-> mmcif task console log, as this is a long task with non-verbose jobs, and not obvious that it is done. Also timestamps might help here.

**Comment by tkrojer** [comment]
sorted; no more improvements/ changes planned at this point.
