### ISSUE TITLE
giant.make_restraints - capture & communicate reasons for failure

### ISSUE THREAD

**Issue by tkrojer** [xchem/XChemExplorer#216]
preparation of files for 'pandda refinement' fails in cases where only a ligand was placed, but there are no displaced water molecules or side chain movements, i.e. when there are no alternative conformations close to the ligand. The logfile is not very informative, but the command line error message is clearer (see below). It would be helpful for users and developers if the reason for why it failed would be better communicated.

multi-state-restraints.log:
----------------------------------------------- *** ------------------------------------------------
---                       Checking the continuity of the protein backbone                        ---
----------------------------------------------- *** ------------------------------------------------

No breaks in the backbone - hooray! (nothing needs to be done here)

----------------------------------------------- *** ------------------------------------------------
---                       Generating restraints for duplicated conformers                        ---
----------------------------------------------- *** ------------------------------------------------

No duplicated conformers (no restraints created)

----------------------------------------------- *** ------------------------------------------------
---                           Generating occupancy-constrained groups                            ---
----------------------------------------------- *** ------------------------------------------------

Looking for ligands with resname DRG or FRG or LIG or UNK or UNL

No matching residues were found (no occupancy constraints created)

command line message:
Creating occupancy group based on: model(),chain(B),resseq(   1),icode( ),resname(LIG),altloc(B),name(*)
- this residue is part of alternate conformer B
- there are 1 atom_groups in this group
Looking for overlapping groups of residues with different alternate conformers:
Occupancy groups for this residue
- 0 overlapping group(s) found
...no overlapping groups found.
- not creating any occupancy groups for this residue

**Comment by nelse003** [comment]
Solved, Raise agian if needed
