### ISSUE TITLE
change labxchem default project directory name

### ISSUE THREAD

**Issue by tkrojer** [xchem/XChemExplorer#220]
The default labxchem project directory name is initial_model which is, unsurprisingly, confusing as the directory contains all PDB files, from inital refinement to deposition. We will rename is to model_building (to be confirmed) and XCE will then recognise is at default when xce is opened in the respective labxchem visit.

**Comment by nelse003** [comment]
Prepare visit script is update, but xce lags behind

**Comment by nelse003** [comment]
model_building

**Comment by tkrojer** [comment]
implemented in v1.3.8.7 (06/06/2019)
