### ISSUE TITLE
pandda refinement error due to existing directory in cootOut folder

### ISSUE THREAD

**Issue by tkrojer** [xchem/XChemExplorer#225]
The error below has appeared a few times, but needs to be more informative. It is most likely only a symptom, while the real cause could be a previously failed refinement attempt.

Traceback (most recent call last):
  File "/home/XXX/XChem1.2.1/XChemExplorer-1.2.1/lib/XChemCootNew.py", line 1106, in REFINE
    os.mkdir(os.path.join(self.project_directory,self.xtalID,'cootOut','Refine_'+str(self.Serial)))
OSError: [Errno 17] File exists: '/home/XXX/processing/analysis/initial_model/XXX-x0065/cootOut/Refine_12'
Traceback (most recent call last):
  File "/home/XXX/XChem1.2.1/XChemExplorer-1.2.1/lib/XChemCootNew.py", line 1106, in REFINE
    os.mkdir(os.path.join(self.project_directory,self.xtalID,'cootOut','Refine_'+str(self.Serial)))
OSError: [Errno 17] File exists: '/home/XXX/processing/analysis/initial_model/XXX-x0065/cootOut/Refine_12'

**Comment by nelse003** [comment]
Fix only error message!

**Comment by tkrojer** [comment]
This should not be an issue any more. An exception has been added to XChemCootNew.py at some point during development of v1.3 (apparently not documented)
v1.3.8.3 also contains a warning message to check folder
