### ISSUE TITLE
Generate all enantiomers of a ligand (RDKit) - might be done

### ISSUE THREAD

**Issue by reskyner** [xchem/XChemExplorer#23]
Should be relatively straight-forward for chiral (R/S) and cis- / trans (E/Z) isomerism;
Remove stereochemistry (@ and / from SMILES string)
Generate graph
Assign possible stereocentres (use same notation as SMILES string for order of atoms
This data is stored as a string representation of equivalent length to the SMILES string, using : 0 = atom/bond not stereo- relevant, 1 = atom/bond is chiral centre, 2 = atom/bond is double bond (E/Z) - double check placement of @'s and /'s
To reconstruct the possible stereoisomers:
Generate all possible combinations and re-insert into SMILES strings

**Comment by abradle** [comment]
I have code that does this. And it was discussed this week how to improve. Assign me and I can add in.

**Comment by reskyner** [comment]
@tkrojer Can you remember what this was actually for? I pulled it from my old confluence page, which was compiled from a spreadsheet you showed me a very long time ago.

**Comment by nelse003** [comment]
As far as I know the logic for this was so that when a ligand that could have multiple enantiomers, both could be loaded into pandda inspect, and thus the most appropriate one fitted. I assumed tie anthony's code to a button in inspect/ refinement interface that say "Load alternate enatiomer". Sarah Kidd has examples.

**Comment by reskyner** [comment]
Thanks Elliot - I'll email the Kiddster and ask her for some. @abradle we can take this offline, or set up a project to work on it. I'm happy to do the interfacing into XCE.

**Comment by abradle** [comment]
For the generation of the Enantiomers. https://github.com/rdkit/UGM_2017/blob/master/Notebooks/Landrum_Whats_New.ipynb

**Comment by abradle** [comment]
Fixed by https://github.com/xchem/XChemExplorer/pull/79
