### ISSUE TITLE
PanDDA export not finding mtz files

### ISSUE THREAD

**Issue by reskyner** [xchem/XChemExplorer#24]
"I’m having a problem running panda.export in XCE. When I run 'Export ALL PANDDA models’ I get several error messages (part of terminal output attached and slightly modified to change the target name).

It seems that there is some confusion about where to find the appropriate files for refinement:

==> XCE: ERROR!!! XFB1-x0714: cannot start refinement because XFB1-x0714.free.mtz is missing in /dls/labxchem/data/2017/lb16946-1/processing/analysis/initial_model/XFB1-x0714

But when I ‘ls /dls/labxchem/data/2017/lb16946-1/processing/analysis/initial_model/XFB1-x0714’ I find the mtz.

Any pointers on what might be the source of the problem would be appreciated."

1) Close any XCE session
2) Make a copy of data source
> At: processing/database
3) Open the data-source file in sqlite browser:
> sqlite browser available at: /dls/science/groups/i04-1/software/sqlitebrowser-3.8.0/sqlitebrowser
4) Check whether the files have the correct path.
> The DataProcessingPathtoMTZfile column in main table (but also sanity check other mtz columns)
> Also sanity check the pandda table.
5) Change paths if incorrect, and/or run "Data Source menu: update data source from file system" from within XCE
6) Try rerunning pandda.

Quicker option: try step (5) before (3) and (4)

**Comment by nelse003** [comment]
I've tried testing this by using an older version of the database file which semed clean. But i still get the missing mtz issue, after rerunning pandda analyse and pandda inspect.

**Comment by nelse003** [comment]
Looking at the mtz files between a xtal that s working, and xtal is not. mtzdmp fails only on the xtal that isn't working.

**Comment by nelse003** [comment]
Looking at the dimple logs: initial_model/BCL6-x0724/dimple/dimple_rerun_on_selected_file/dimple/dimple.log and equivalent for x0714. I cannot see any difference in the R free generation, or any differnce in the dimple log. @tkrojer Ideas regarding what might be failing in dimple/ processing w.r.t the failing prepared.mtz

**Comment by nelse003** [comment]
I'll update Matt that we are looking to this.

**Comment by nelse003** [comment]
If we rerun dimple, can we point to new free file without rerunning pandda?

**Comment by RodriguesMJ** [comment]
Thanks for looking into this!

**Comment by reskyner** [comment]
Elliot will discuss with tobias

**Comment by nelse003** [comment]
Closing: Error is because of dimple inconstencies due to lack of cofactor restraints.

See #50 #49
