### ISSUE TITLE
Testing implementation of phenix.refine for structures in XCE

### ISSUE THREAD

**Issue by reskyner** [xchem/XChemExplorer#28]
Issues likely to arise with export step.

**Comment by reskyner** [comment]
Take phenix.refine checkbox off

**Comment by nelse003** [comment]
Had issue with user trying phenix refine. We need to remove/ renmae checkbox until (if desired) implement phenix refinement using phenix  version of giant.quick_refine

**Comment by nelse003** [comment]
Refinemnt is now somewhat implemented, but failure occurs with giant.split_conformations. The issue can be mitigated by running with prune duplicates= flase. I need to investigate if a better solution exists before implementing.
