### ISSUE TITLE
Run XCE locally

### ISSUE THREAD

**Issue by reskyner** [xchem/XChemExplorer#31]
Ability for users to download and submit directly to cluster. 

Patrick sent Rachael a VM which works for linux. Will test the configuration properly during build next week. 

Rachael tested on MAC, and didn't work. 

Typical errors during install (e.g. numpy library) - will set up a docker container for build

**Comment by reskyner** [comment]
I've added an install script that will setup ccp4 and update pandda automatically in a git copy of the XCE repo. I've also added a script to setup directory mounting for ssh via the example in the VM that Paddy and Tobias set up. 

However, I can't seem to get qsub to be detected. Any ideas, anybody?

**Comment by reskyner** [comment]
Frank wants to use the virtual machine setup for this, so will update all of that with Patricks help.

Can also put some 'unofficial' install instructions for local machine somewhere, but make sure that we indicate using virtual machine as recommended route.

Pros:
- refinement view runs quicker

Cons:
- loading files etc. takes longer

**Comment by reskyner** [comment]
Thinking about this - **I would rather not deploy as a VM, as a personal preference, so would like to reopen this discussion to see if we can just do it properly, relatively quickly... quick fixes always come back to bite us in the ass!**

I think what we need to do is fix how the datasource treats paths (relative instead of absolute) - https://github.com/xchem/XChemExplorer/issues/40 - and fix the qsub command - will add issue.

**Comment by reskyner** [comment]
Double checked the old VM, which had an old version of XCE in it. qsub doesn't work there either, so I can only conclude that it probably never has, unless someone tells me otherwise...

So, I need to recode the qsub stuff, I guess. 

This may take longer than originally anticipated. 

@tkrojer, do you remember if this ever worked?

**Comment by reskyner** [comment]
https://github.com/xchem/XChemExplorer/issues/98

**Comment by reskyner** [comment]
So, although XCE will ‘run’ locally, the code is not there to submit jobs via ssh to the cluster, and I suspect it never has been. For the refinements or anything else to be useful, this needs to be implemented. This means I will have to implement this for every bit of the code where jobs can be submitted to the cluster, so that the whole pipeline can be run in the VM (otherwise, what’s the point?). I will separate this into a ticket for each stage, once I have trawled through and worked out which bits I need to change. I’ve done dimple and pandda.analyse so far. It took 2 days. This will take at least a couple of weeks.

**Comment by reskyner** [comment]
CCP4 is still interfering with COOT, but using the install script I wrote seems to solve it, for now...

I will make sure this is implemented in the VM.

To Do:
- unset LD_LIBRARY_PATH before remote submission within COOT interface, and reset afterwards
- get rid of some print statements that were used for testing
- deploy a version of the VM to Paddy and Alice for testing
- generate restraints remote submission

**Comment by nelse003** [comment]
Conor is looking at containers now.  Almost certainly likely to be better.  So kill this ticket.
