### ISSUE TITLE
pdbx_audit_support categories now required for PDB deposition but not included in XCE

### ISSUE THREAD

**Issue by Daren-fearon** [xchem/XChemExplorer#399]
pdbx_audit_support categories now required for PDB deposition but not included in XCE:

"As for pdbx_audit_support category, it's describing the grant support of the project and now mandatory for wwPDB submission, please use group deposition template from the latest version of pdb_extract, so that the category will be included in the mmcif format model file. The category reads like
loop_
_pdbx_audit_support.ordinal
_pdbx_audit_support.funding_organization
_pdbx_audit_support.grant_number
_pdbx_audit_support.country
1 'National Institutes of Health/National Institute of General Medical Sciences' '1R01GM072999-01' 'United States'
If there's no specific funding agency, but support is from company, the it can be stated as 'other private', but please include the country
"

Work around from Andre Godoy:

tar -xf *.tar.bz2
mkdir tmp1
mv *_sf.mmcif tmp1
for f in *.mmcif; do
cat <<EOF >> $f
#
loop_
    _pdbx_audit_support.ordinal
    _pdbx_audit_support.funding_organization
    _pdbx_audit_support.grant_number
    _pdbx_audit_support.country
    1  'National Institute for General Medical Sciences' '1R01GM072999-01' 'United States'
EOF
done
mv tmp1/* .
rm -r tmp1
tar -cvjf grantupdated.tar.bz2 *mmcif index.txt

you can add more grants in the format you wish right below the example with number 2, 3..
Not the best solution for XCE, but I hope it helps

**Comment by tkrojer** [comment]
implemented in v1.7.34 (25/06/2021)
