### ISSUE TITLE
Clean up DLS software folder

### ISSUE THREAD

**Issue by nelse003** [xchem/XChemExplorer#41]
DLS software folder still has too many xce-dev, pandda-update/ pandda-install folders. We need to remove/ store old things in a different place.

Sorry if incorrect place for tracking this issue.

**Comment by reskyner** [comment]
I agree... 

@tkrojer, can you move your stuff by Monday please?

I'll move the XCE_new folder to be XCE when this is done.

**Comment by tkrojer** [comment]
removed XChemExplorer-dev & XChemExplorer-beta
