### ISSUE TITLE
Clean up of lb-133853: FAM83BA

### ISSUE THREAD

**Issue by nelse003** [xchem/XChemExplorer#46]
- 2 time seperated pandda runs.

- One exported, One inspected

Need to check pandda version and plan how Dan can continue with & clean up

**Comment by nelse003** [comment]
Dan would like to check status of data source for the first pandda run (different crystal form between runs), then rerun pandda, to help clean up the issues that existed due to starting over the summer of "xce bug fixing".

**Comment by nelse003** [comment]
With Romain

**Comment by tkrojer** [comment]
All structures from inital fragment screen have been deposited.
