### ISSUE TITLE
 Multiple cif files to define co-factors/ already bound ligands

### ISSUE THREAD

**Issue by nelse003** [xchem/XChemExplorer#49]
Currently any co-factor restraints need to be supplied by adjusting the cif file of the bound ligand. This is awkward as it cannot be done within the xce interface, and is inconsitent with crystallogrpahic protocol.

Solution: Ability for user to supply/ generate a/multiple cif file for any co-factors defined. As option in xce interface.

**Comment by nelse003** [comment]
The problem is not with pandda.export but with XCE and that there is no ability to add additional CIF files for a structure beyond those of the soaked ligand.

I can tell you the source of the problem, which might enable you to make a workaround, and will provide a starting point for TobRachEllio to program an XCE solution. 

The problem: ONLY ONE CIF FILE CAN BE PROVIDED TO REFMAC. 

For refmac to refine a structure with two or more ligands, the individual cif files have to be merged into one file.

You can do that with a VERY archaic program called LIBCHECK from CCP4.

LIBCHECK <<eof
_DOC N
_FILE_L file1.cif
_FILE_L2 file2.cif
_FILE_O out_prefix
_END
eof

which will create a file called out_prefix.lib, which you can rename to out_prefix.cif. 

You’ll have to do this for each ligand in each dataset

Dataset1: main.cif + fragment1.cif > combined1.cif
Dataset2: main.cif + fragment2.cif > combined2.cif
Dataset3: main.cif + fragment3.cif > combined3.cif
Dataset4: main.cif + fragment4.cif > combined4.cif

which of course is easily scriptable…

**Comment by phraenquex** [comment]
a) Pretty sure you can simply concatenate all ligand cif files (that's the whole point of the CIF format.)

b) co-factor restraints already exist in the CCP4 monomer library:  it would be very rare to need to generate from scratch.

This feels very automatable:  any .cif files in the same place as the reference pdb simply get strung onto the end of the fragment.cif file.

**Comment by wojdyr** [comment]
> a) Pretty sure you can simply concatenate all ligand cif files (that's the whole point of the CIF format.)
> 

in general it's not that straightforward, link IDs must be unique so if the same IDs are used in two files they must be renamed.

**Comment by tkrojer** [comment]
A recurring issue amongst users:
Users can already provide additonal CIF files during initial refinement with DIMPLE. However, it is not necessarily obvious to them how XCE processes the infomation. It was suggested to present the presence of a suitable CIF file (same name as PDB file) during initial refinement by showing it in the combobox, e.g.
model1.pdb/ model1.cif
model2.pdb/ NO CIF
model3.pdb/ model3.cif
This will of course only help during initial refinement. What should then happen is:
- as part of initlal refinement, copy the used CIF file in the reference directory into the respective sample directory as dimple.cif
- if the ligand/ fragment restraints were already generated, merged dimple.cif with them
- if the ligand/ fragment restraints are not there yet, then merge dimple.cif with them when they get created.

**Comment by tkrojer** [comment]
implemented in v1.3.8.12 (10/09/2019)
