### ISSUE TITLE
Restraints generation defaulting to grade

### ISSUE THREAD

**Issue by reskyner** [xchem/XChemExplorer#61]
Used to default to acedrg. Double check (probably dictionary enumeration problem)

**Comment by nelse003** [comment]
Note grade is listed in the preferences window. Not sure if was a choice or an error

**Comment by reskyner** [comment]
@tkrojer - did you change it, or did I fuck it up during the update?

**Comment by reskyner** [comment]
https://github.com/xchem/XChemExplorer/pull/93
