### ISSUE TITLE
Compile Test shouldn't catch exception

### ISSUE THREAD

**Issue by abradle** [xchem/XChemExplorer#83]
Not sure why it does? Whole purpose is to throw a non-zero exit code if it fails. Very misleading as is.

**Comment by reskyner** [comment]
https://github.com/reskyner/XChemExplorer/commit/3dcc9a479b805e0a816bb8254a0d7c2971a6c574

**Comment by reskyner** [comment]
https://travis-ci.org/reskyner/XChemExplorer/builds/288576773
