### ISSUE TITLE
Update EDSTATS on CCP4 @ DLS

### ISSUE THREAD

**Issue by nelse003** [xchem/XChemExplorer#92]
Rachael: 
Assuming as you have folder access only , this will have to be you to sort.

**Nick**

So... the actions are that 
* we need to get the latest EDstats onto the XCE/pandda path
He sent me an updated version — it’s just a PERL script. You can drop that into the CCP4 directory in place of the old one. SHOULD just need to find the equivalent files (3 files) in the CCP4 distribution and replace them.

Will forward to Rachaelliot for testing.
* we need to update the keywords being fed to EDstats (or is that PanDDA?)
No need to update any keywords — small chains will be automatically assigned to the nearest chain. 

We should look at automatically assigning the “right" chain ID to a ligand in coot when it’s built (during pandda.inspect) though, since this would kill the problem at its source.

**Comment by reskyner** [comment]
Is there a plan for this to go into a ccp4 update. 

The problem is that we then have to distribute these files, providing we eventually sort out remote access. 

I'll do it, but I'm not very keen on making non-standard alterations that aren't really under our control.

**Comment by reskyner** [comment]
Done.

**Comment by nelse003** [comment]
Hi Ian,

Thanks for updating Nick (and thereby XChem team) w.r.t the updates required for EDSTATS.

Just want to check whether/ what release these updates will go into CCP4 distribution?

Such that we do not need to continue to update the version of CCP4 that XChem Explorer at diamond light source uses.

Thanks

Elliot
