### ISSUE TITLE
Coot crashes when doing real space refine in the groud state modelling tool

### ISSUE THREAD

**Issue by PatrickMCollins** [xchem/XChemExplorer#97]
Confirmed by Tobias, and also observed by users:

Launching coot with the ground state interface, when I try to real space refine a residue in coot, and then drag a very different pose for a residue, coot hangs, and becomes unresponsive.

If I do the exact same thing in the regular xce coot interface, it works fine.

Tobias: "The interface is essentially a clone of all the other interface so it’s not entirely clear what goes wrong."

It hangs every time reproducibly when using the ground state building interface. As far as I can tell, it is the exact same version of coot that is being loaded by both XCE modules. I tried restating my linux box, and tried it on nx.diamond instead in case graphics or something else weird, but the problem persists.

There are no errors, just hanging.

**Comment by joserbngithub** [comment]
I just saw it happening as well.  I tried to move one residue (only one) while doing real space refine and it stalled on me.

**Comment by nelse003** [comment]
Is the error reproducible if all maps (excpet active) are closed from display manager?

**Comment by joserbngithub** [comment]
Yes, I just had 1 map in the display manager, had gotten rid of the many that open up automatically.

**Comment by tkrojer** [comment]
Soved. See Finishing reference model: Coot crashes during real-space... #142 #142
