### ISSUE TITLE
refinement from coot doesn't run via ssh qsub (virtualmachine)

### ISSUE THREAD

**Issue by PatrickMCollins** [xchem/XChemExplorer#98]
Problem with refining on the cluster over ssh from the coot tool (I think this used to work…)

In the preferences I’ve ticked “remote qsub”, with the my fedid entered into the field:
ssh zpo15726@nx.diamond.ac.uk 'module load global/cluster; qsub'

When I click Refine from xce-coot, I get :

==> XCE: writing refinement shell script to/dls/labxchem/data/2017/lb16949-4/processing/analysis/initial_model/OXA10-x0007/Refine_7/refmac.csh
==> XCE: changing directory to /dls/labxchem/data/2017/lb16949-4/processing/analysis/initial_model/OXA10-x0007/Refine_7
==> XCE: starting refinement on cluster
sh: 1: qsub: not found

And then it moves on without refinement. It should be using the remote qsub command.

**Comment by reskyner** [comment]
I'll have a look next week on my XCE day :)

**Comment by reskyner** [comment]
It's not picking up the change to fedID in the preferences box, for some reason:

ssh <dls fed ID>@nx.diamond.ac.uk 'module load global/cluster; qsub'

**Comment by reskyner** [comment]
Traceback (most recent call last):
  File "/home/uzw12877/XCE_rachael_branch/XChemExplorer/XChemExplorer.py", line 659, in run_qsub_remotely
    self.remote_qsub_submission = str(self.remote_qsub_command.text())
RuntimeError: wrapped C/C++ object of type QLineEdit has been deleted

**Comment by PatrickMCollins** [comment]
for the fedid change, I think I have seen that before - opening and closing the preferences box and trying again might have worked for me.

Also, you are getting a different error, like it's actually running the remote_qsub_submission thing. Mine seemed not to look for it, and simply try vanilla qsub...

**Comment by reskyner** [comment]
Found why it wasn't submitting to remote cluster - remote cluster was part of an elif statement, forcing it to always be local if qsub software is present. 

New error:

```
==> XCE: starting refinement on remote cluster
ssh: /home/xchemuser/local/ccp4/ccp4-7.0/lib/libcrypto.so.1.0.0: no version information available (required by ssh)
ssh: /home/xchemuser/local/ccp4/ccp4-7.0/lib/libcrypto.so.1.0.0: no version information available (required by ssh)
OpenSSL version mismatch. Built against 1000207f, you have 100010af
```

**Comment by reskyner** [comment]
This is an error related directly to the VM. 

I will try a fresh build... this is weird. SSH was working for pandda and dimple a few days ago.

**Comment by reskyner** [comment]
CCP4 is still interfering with COOT, but using the install script I wrote seems to solve it, for now...

I will make sure this is implemented in the VM.

To Do:
- unset LD_LIBRARY_PATH before remote submission within COOT interface, and reset afterwards
- get rid of some print statements that were used for testing
- deploy a version of the VM to Paddy and Alice for testing
- generate restraints remote submission

**Comment by tkrojer** [comment]
There are no future plans to support XCE via VMs.
